name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.11.0'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Debug environment
      run: |
        node --version
        npm --version
        ls -la
        ls -la src/
    
    - name: Run linter
      run: npm run lint
    
    - name: Build project
      run: npm run build
    
    - name: Debug build output
      run: |
        ls -la dist/
        
    - name: Run tests
      run: npm test